name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your repository's main branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        sudo docker --version
        sudo docker build -t my-django-app .
      working-directory: ./  # Change to your code directory

  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Stop Old Server
      run: |
        echo "Stopping Old Server..."
        sudo docker stop my-django-app || true  # Ignore if container doesn't exist
        sudo docker rm my-django-app || true  # Ignore if container doesn't exist
      working-directory: ./  # Change to your code directory

    - name: Deploy Docker container
      run: |
        echo "Deploying Docker container..."
        sudo docker run --name my-django-app -p 8000:8000 -d my-django-app
        sudo docker ps
      working-directory: ./  # Change to your code directory
